// Original questions written for this curriculum. No question is represented as an official PYQ.
const rows = [
	[
		"p04",
		"The Preamble is best described as:",
		[
			"An independent source of every executive power",
			"Part of the Constitution and an aid to interpretation",
			"A text that cannot be amended under any circumstances",
			"A replacement for Part III",
		],
		1,
		"The Preamble is part of the Constitution and guides interpretation. It is not an independent grant of all powers; amendments remain subject to basic structure; enforceable rights are specified elsewhere.",
	],
	[
		"p05",
		"For a bill reorganising the boundaries of a state under Article 3, which statement is correct?",
		[
			"The affected state must always consent",
			"The President must recommend introduction and the state is given an opportunity to express views",
			"A referendum in the state is invariably mandatory",
			"Every such change necessarily requires Article 368 ratification",
		],
		1,
		"Article 3 requires the President’s recommendation and reference to affected state legislatures for their views within the specified period. Consent and a referendum are not mandatory merely under this provision; Article 4 covers specified consequential changes.",
	],
	[
		"p06",
		"An OCI cardholder is, solely by virtue of that registration:",
		[
			"Automatically entitled to vote in Lok Sabha elections",
			"A holder of full dual citizenship",
			"Not thereby granted Indian voting citizenship",
			"Automatically eligible to become President",
		],
		2,
		"OCI is not full dual citizenship and does not itself confer political citizenship rights such as voting. Eligibility for constitutional offices cannot be inferred from OCI registration.",
	],
	[
		"p07",
		"Consider: 1. Article 19 freedoms are available to citizens. 2. Article 21 protects persons, not only citizens. Which is correct?",
		["1 only", "2 only", "Both 1 and 2", "Neither"],
		2,
		"Both are correct. Different Fundamental Rights have different right-holders; it is unsafe to describe all Part III rights as citizen-only.",
	],
	[
		"p07",
		"Which comparison of writ powers is accurate?",
		[
			"Article 32 extends to all ordinary contractual disputes automatically",
			"Article 226 can address Fundamental Rights and other legal purposes",
			"Only the Supreme Court can issue habeas corpus",
			"Article 226 is itself located in Part III",
		],
		1,
		"Article 226 permits High Court writs for Fundamental Rights and other legal purposes, within applicable limits. Article 32 addresses enforcement of Fundamental Rights; High Courts can also issue habeas corpus; Article 226 is outside Part III.",
	],
	[
		"p08",
		"Directive Principles are:",
		[
			"Directly enforceable in exactly the same way as all Fundamental Rights",
			"Not directly enforceable by courts, but fundamental in governance",
			"Merely executive circulars",
			"A power to disregard every Fundamental Right",
		],
		1,
		"Article 37 distinguishes non-justiciability from constitutional importance. Directive Principles are constitutional, not executive circulars, and do not automatically override all rights.",
	],
	[
		"p09",
		"The educational Fundamental Duty concerning children aged six to fourteen was added by the:",
		["42nd Amendment", "44th Amendment", "86th Amendment", "101st Amendment"],
		2,
		"The 86th Amendment added Article 51A(k). The 42nd introduced the original ten duties; the other listed amendments do not account for this addition.",
	],
	[
		"p10",
		"An Article 368 amendment requiring no state ratification still generally needs:",
		[
			"Only a majority of members present and voting",
			"A majority of total membership and two-thirds of those present and voting in each House",
			"Only Rajya Sabha approval",
			"A joint sitting in every case",
		],
		1,
		"The special majority has two limbs and must be met separately in each House. Joint sitting is not a route for constitutional amendment bills.",
	],
	[
		"p11",
		"The basic-structure doctrine principally limits:",
		[
			"Only municipal taxation",
			"Parliament’s constitutional amending power",
			"All political debate",
			"Only the President’s election",
		],
		1,
		"The doctrine limits constitutional amendment so that the foundational constitutional order is not destroyed. It is not a ban on debate or a rule confined to one office.",
	],
	[
		"p13",
		"Residuary legislative powers under the Indian Constitution are vested in:",
		[
			"Every Gram Sabha",
			"Parliament",
			"Only state legislatures",
			"The Finance Commission",
		],
		1,
		"Article 248 read with the Union List provides Parliament’s residuary legislative power. Local bodies and the Finance Commission do not possess that authority.",
	],
	[
		"p15",
		"Which institution has its constitutional basis in Article 263?",
		[
			"Inter-State Council",
			"Every Zonal Council",
			"Finance Commission",
			"GST Council",
		],
		0,
		"Article 263 concerns the Inter-State Council. Zonal Councils have statutory foundations; Articles 280 and 279A concern the other two bodies.",
	],
	[
		"p16",
		"Under Article 359, suspension of the right to move courts cannot cover enforcement of:",
		[
			"Articles 20 and 21",
			"Only Article 19",
			"Every provision of Part III without exception",
			"Only Article 32 irrespective of other rights",
		],
		0,
		"The Constitution protects Articles 20 and 21 from the relevant Article 359 order. Article 358 and Article 359 should not be conflated.",
	],
	[
		"p17",
		"A presidential ordinance under Article 123:",
		[
			"Can be used as an unrestricted permanent substitute for Parliament",
			"Requires the constitutionally specified session situation and necessity for immediate action",
			"Is immune from all constitutional scrutiny",
			"Can amend the Constitution through Article 368 without Parliament",
		],
		1,
		"The ordinance power is conditional and temporary. Ordinances are not constitutionally unlimited, immune from scrutiny or a substitute for the Article 368 process.",
	],
	[
		"p18",
		"Which voters participate in the Vice-President’s election?",
		[
			"Only elected Lok Sabha members",
			"Members of both Houses including nominated members",
			"All state assembly members but no MPs",
			"All Indian citizens directly",
		],
		1,
		"Members of both Houses elect the Vice-President; nominated members participate. State assemblies do not form part of this electoral college.",
	],
	[
		"p20",
		"The Union Council of Ministers is collectively responsible to:",
		[
			"Lok Sabha",
			"Rajya Sabha alone",
			"The Supreme Court as a political confidence chamber",
			"All state assemblies jointly",
		],
		0,
		"Article 75 locates collective political responsibility in Lok Sabha. Other institutions perform different constitutional functions.",
	],
	[
		"p22",
		"A joint sitting under Article 108 is NOT the constitutional route for resolving disagreement on:",
		[
			"An ordinary bill in a qualifying deadlock",
			"A constitutional amendment bill",
			"A qualifying ordinary non-financial bill",
			"Any ordinary bill merely because Rajya Sabha considered it first",
		],
		1,
		"Constitutional amendment bills and Money Bills are excluded from the joint-sitting route. The options concerning ordinary bills do not identify a universal exclusion.",
	],
	[
		"p23",
		"A parliamentary committee report ordinarily:",
		[
			"Enacts a new law immediately",
			"Provides findings and recommendations rather than itself legislating",
			"Replaces the Appropriation Act",
			"Dissolves Lok Sabha",
		],
		1,
		"Committees scrutinise and recommend. Their reports do not ordinarily enact legislation, authorise all expenditure or dissolve a House.",
	],
	[
		"p26",
		"Which pairing is correct?",
		[
			"Supreme Court retirement—62; High Court—65",
			"Supreme Court retirement—65; High Court—62",
			"Both invariably retire at 60",
			"Both hold judicial office for life",
		],
		1,
		"The constitutional retirement ages are 65 for Supreme Court judges and 62 for High Court judges. Neither life tenure nor the reversed pairing is correct.",
	],
	[
		"p27",
		"Placement of a law in the Ninth Schedule after 24 April 1973 means:",
		[
			"Complete immunity from every constitutional challenge",
			"Its protection remains subject to the relevant basic-structure scrutiny",
			"Automatic repeal of Article 32",
			"It cannot be examined by any High Court for any purpose",
		],
		1,
		"I. R. Coelho explains why later Ninth Schedule placement does not create unconditional immunity. The other options overstate protection or invent repeal.",
	],
	[
		"p33",
		"A Legislative Council and a Legislative Assembly disagree on an ordinary bill. Which assertion is incorrect?",
		[
			"Their powers are not generally equal",
			"The Council has a constitutionally limited delaying role",
			"A state-level joint sitting necessarily resolves the deadlock",
			"The applicable procedure differs from Article 108",
		],
		2,
		"There is no constitutional state-level joint sitting equivalent to Article 108. The Council’s role and the assembly’s predominance must be read under the state legislative provisions.",
	],
	[
		"p35",
		"After L. Chandra Kumar, tribunal decisions are:",
		[
			"Categorically beyond High Court judicial review",
			"Subject to the preserved constitutional judicial-review framework",
			"Equivalent to constitutional amendments",
			"Automatically binding on all courts in all matters",
		],
		1,
		"The judgment preserved High Court review under Articles 226/227 and the constitutional structure. Tribunal specialisation does not abolish that review.",
	],
	[
		"p38",
		"The Eleventh Schedule lists subjects associated with:",
		[
			"Panchayats",
			"Only the Union Cabinet",
			"Municipalities exclusively",
			"The Supreme Court’s appellate powers",
		],
		0,
		"The Eleventh Schedule lists 29 Panchayat-related subjects. Municipal subjects are in the Twelfth Schedule; devolution still depends on the constitutional and state-law framework.",
	],
	[
		"p41",
		"The Sixth Schedule relates to tribal areas in:",
		[
			"All states without distinction",
			"Assam, Meghalaya, Tripura and Mizoram",
			"Only Rajasthan and Gujarat",
			"Only Union territories",
		],
		1,
		"The Sixth Schedule applies to tribal areas in the four specified states. Do not substitute the different Fifth Schedule framework.",
	],
	[
		"p42",
		"Local-body elections are generally administered by:",
		[
			"The Election Commission of India for every municipality",
			"The relevant State Election Commission",
			"The Finance Commission",
			"The UPSC",
		],
		1,
		"Constitutional provisions create State Election Commissions for local elections. ECI’s Article 324 remit concerns other specified elections.",
	],
	[
		"p44",
		"A member of a State Public Service Commission is appointed by the Governor, but removal under Article 317 is by the:",
		[
			"Chief Minister acting alone",
			"President",
			"State Finance Commission",
			"District Judge",
		],
		1,
		"Appointment and removal authorities differ. Article 317 provides the President’s role and the prescribed process.",
	],
	[
		"p45",
		"Vertical and horizontal tax devolution respectively concern:",
		[
			"Union–state sharing; distribution among states",
			"Distribution among villages; distribution among ministries",
			"Two names for the same allocation",
			"Only GST rates; only customs rates",
		],
		0,
		"Vertical devolution allocates between levels; horizontal devolution distributes among states. Neither term simply means setting a tax rate.",
	],
	[
		"p46",
		"In the GST Council’s constitutional weighted-voting arrangement, the Centre has:",
		[
			"One-third of weighted votes",
			"Two-thirds of weighted votes",
			"All votes",
			"No vote",
		],
		0,
		"The Centre has one-third and states together two-thirds; a three-fourths weighted majority of members present and voting is prescribed for decisions.",
	],
	[
		"p49",
		"The 105th Amendment is especially relevant when studying:",
		[
			"State identification of socially and educationally backward classes",
			"Creation of the Election Commission in 1950",
			"Abolition of every state legislature",
			"Replacement of Article 21 by a Directive Principle",
		],
		0,
		"It is important to the state identification framework under Article 342A. The other statements are unrelated or false.",
	],
	[
		"p51",
		"CAG audit reports are best understood as:",
		[
			"A replacement for legislative scrutiny",
			"Inputs to public financial accountability and legislative examination",
			"Criminal convictions against everyone mentioned",
			"Prior permission for every expenditure item",
		],
		1,
		"Audit reports support accountability and committee scrutiny. They are not inherently convictions or a system of prior authorisation for every payment.",
	],
	[
		"p54",
		"NITI Aayog was established through:",
		[
			"An executive resolution",
			"Article 280 itself",
			"A Supreme Court criminal judgment",
			"A constitutional provision establishing every ministry",
		],
		0,
		"NITI Aayog is an executive institution. Article 280 concerns the Finance Commission; the other instruments do not establish it.",
	],
	[
		"p57",
		"A request under RTI ordinarily seeks:",
		[
			"Existing information within the Act’s framework",
			"An unlimited right to have new research created",
			"Automatic success in any service dispute",
			"A judicial verdict from the information officer",
		],
		0,
		"The Act concerns access to information and records within its framework. It is not a general right to compel fresh research or obtain unrelated adjudication.",
	],
	[
		"p64",
		"Which statement about the 97th Amendment requires correction?",
		[
			"It added Article 43B",
			"It concerned cooperative societies",
			"Its original Part IXB scheme applies identically to every state cooperative without regard to the 2021 judgment",
			"It amended Article 19(1)(c)",
		],
		2,
		"Rajendra N. Shah (2021) requires attention to the state-cooperative portion and ratification issue. The other statements identify components of the amendment.",
	],
	[
		"p65",
		"Which is correct?",
		[
			"The Constitution declares Hindi the national language",
			"Union official-language provisions and Eighth Schedule inclusion are distinct matters",
			"All Eighth Schedule languages are automatically classical languages",
			"English use ended automatically in every legal setting after fifteen years",
		],
		1,
		"Official language, scheduled language and classical status are different categories. The Constitution does not declare a national language; the statutory framework also matters for English.",
	],
	[
		"p76",
		"The 91st Amendment removed which former anti-defection exception?",
		[
			"The split exception",
			"All provisions concerning merger",
			"All judicial review",
			"Every rule concerning nominated members",
		],
		0,
		"The former split exception was removed, while the merger provision has its specified threshold. Judicial review and other member categories were not abolished wholesale.",
	],
	[
		"e01",
		"A policy raises real GDP but leaves health access and severe regional disparities unchanged. Which conclusion is justified?",
		[
			"Development must have improved in every dimension",
			"Output growth alone does not establish inclusive development",
			"Real GDP is always meaningless",
			"Regional differences cannot be measured",
		],
		1,
		"GDP growth is informative but not a complete measure of capabilities or distribution. The other options either overclaim or reject useful measurement entirely.",
	],
	[
		"e02",
		"A farmer sells wheat for 100, a mill sells flour for 160, and a baker sells final bread for 250. With no other inputs, total value added is:",
		["510", "250", "160", "100"],
		1,
		"Value added is 100 + (160−100) + (250−160) = 250. Summing all gross sales would double count intermediate production.",
	],
	[
		"e02",
		"Nominal GDP is 240 and real GDP is 200 in compatible units. The GDP deflator is:",
		["83.33", "120", "40", "440"],
		1,
		"Nominal / real × 100 = 240/200 × 100 = 120. Subtraction does not calculate the deflator; reversing the ratio gives a different number.",
	],
	[
		"e02",
		"GDP plus net primary income from the rest of the world gives:",
		[
			"Gross national income",
			"Revenue deficit",
			"Only exports",
			"Consumption of fixed capital",
		],
		0,
		"The domestic-to-national adjustment concerns cross-border primary income. Depreciation is a separate gross-to-net adjustment.",
	],
	[
		"e03",
		"Which is the strongest evidence of meaningful financial inclusion?",
		[
			"An account exists but is inaccessible",
			"Affordable access, regular useful usage and effective grievance redress",
			"Only the number of advertisements",
			"An increase in bank buildings with no service data",
		],
		1,
		"Inclusion concerns access, usage and quality. Account counts or buildings alone do not show that households can use appropriate services.",
	],
	[
		"e04",
		"Out of 1,000 working-age persons, 600 are in the labour force and 60 are unemployed. The unemployment rate is:",
		["6%", "10%", "60%", "54%"],
		1,
		"The unemployment rate uses the labour force denominator: 60/600 × 100 = 10%. Six per cent uses the wrong denominator; 60% is LFPR.",
	],
	[
		"e04",
		"If discouraged jobseekers stop seeking and leave the measured labour force, the unemployment rate may fall even when:",
		[
			"Employment has not increased",
			"Every person obtained a job",
			"The labour force necessarily grows",
			"The definition no longer uses a denominator",
		],
		0,
		"A lower rate can result from labour-force exit rather than job creation. Check participation and employment indicators together.",
	],
	[
		"e05",
		"A bank has enough long-term assets to cover liabilities but cannot meet payments due today. This most directly illustrates:",
		[
			"A liquidity problem",
			"Proof that all assets are worthless",
			"A rise in sovereign GDP",
			"An automatic loan waiver",
		],
		0,
		"Liquidity concerns timely payment capacity. It is distinct from overall solvency, though a liquidity crisis can worsen solvency if assets must be sold at distressed prices.",
	],
	[
		"e05",
		"Other things equal, an RBI open-market purchase of government securities generally:",
		[
			"Injects rupee liquidity",
			"Absorbs rupee liquidity",
			"Directly writes off every private loan",
			"Creates a new tax",
		],
		0,
		"Payment for purchased securities injects liquidity. Sales generally absorb it; neither operation automatically waives loans or enacts taxes.",
	],
	[
		"e05",
		"A bank writes off a bad loan in its accounts. Which inference is unsafe?",
		[
			"Accounting treatment has changed",
			"The borrower’s legal repayment obligation has necessarily been waived",
			"Recovery may still be pursued",
			"A write-off and waiver are distinct",
		],
		1,
		"A write-off is not automatically a waiver. The legal recovery position depends on the applicable arrangement and law.",
	],
	[
		"e06",
		"A higher crop yield necessarily guarantees higher net farm income. This statement is:",
		[
			"Always correct",
			"Incorrect because prices and costs also affect net income",
			"Correct whenever rainfall is high",
			"Correct whenever output is measured in tonnes",
		],
		1,
		"Net income depends on revenue and costs; yield alone cannot establish it. Prices, input costs and market access matter.",
	],
	[
		"e07",
		"An increase in industrial sales revenue proves an equal increase in physical output. This is:",
		[
			"Necessarily true",
			"Not necessarily true because prices and product mix can change",
			"True whenever firms pay tax",
			"True only because revenue is a stock",
		],
		1,
		"Nominal revenue is not a pure volume measure. Revenue is a flow, and taxation does not solve the price/quantity distinction.",
	],
	[
		"e08",
		"A rural road has low toll revenue but large health and market-access benefits. It may be:",
		[
			"Socially valuable even if private cash flows are weak",
			"Worthless by definition",
			"A private public-good contradiction in every case",
			"Automatically free of maintenance costs",
		],
		0,
		"Social appraisal includes benefits not fully captured in toll receipts. Public finance may be justified, but maintenance and appraisal remain essential.",
	],
	[
		"e09",
		"Total expenditure is 1,000, revenue receipts 700 and non-debt capital receipts 50. Fiscal deficit is:",
		["300", "250", "950", "1,750"],
		1,
		"Fiscal deficit = 1,000 − 700 − 50 = 250. Revenue deficit requires revenue expenditure, which is not supplied here.",
	],
	[
		"e09",
		"Fiscal deficit is 250 and interest payments are 90. Primary deficit is:",
		["340", "160", "90", "250"],
		1,
		"Primary deficit = fiscal deficit − interest payments = 160. It isolates the deficit excluding interest payments, not all capital spending.",
	],
	[
		"e09",
		"Which statement is correct?",
		[
			"Debt and deficit are both always annual flows",
			"Public debt is a stock and a fiscal deficit is a flow",
			"Teacher salaries have no possible developmental value because they are revenue expenditure",
			"A budget speech alone is sufficient legal authority for every new tax",
		],
		1,
		"Debt is measured at a point in time and deficit over a period. Accounting classification is not a complete welfare evaluation; legal tax authorisation is separate.",
	],
	[
		"e10",
		"In a PPP, a government guarantee can:",
		[
			"Create a future contingent fiscal liability",
			"Make every project costless",
			"Eliminate all demand risk from society",
			"Replace all contract monitoring",
		],
		0,
		"A guarantee can crystallise into an actual fiscal obligation. Risk allocation changes who bears a risk, not whether the risk exists.",
	],
	[
		"e11",
		"Selling a small minority of government shares without transferring management is necessarily full privatisation. This is:",
		[
			"Correct",
			"Incorrect; disinvestment and transfer of control are distinct",
			"Correct whenever shares are listed",
			"Correct only when the company pays dividends",
		],
		1,
		"A partial disinvestment need not transfer managerial control. Listing or dividend payment does not settle the ownership-control question.",
	],
	[
		"e12",
		"A current-account deficit is necessarily identical to a merchandise trade deficit. This is:",
		[
			"Correct",
			"Incorrect because services and income/transfers also enter the current account",
			"Correct whenever exchange rates float",
			"Correct whenever reserves are positive",
		],
		1,
		"The current account is broader than merchandise trade. Exchange-rate regime and reserve levels do not erase the additional components.",
	],
	[
		"e12",
		"Domestic-currency depreciation may:",
		[
			"Lower import prices in domestic currency in every case",
			"Raise the domestic-currency cost of foreign-currency debt service",
			"Guarantee an immediate trade surplus",
			"Have no possible inflation effect",
		],
		1,
		"Foreign-currency obligations become costlier in domestic currency, other things equal. Export response depends on elasticities, capacity, invoicing and time; inflation effects are possible.",
	],
	[
		"e13",
		"A WTO member’s applied tariff is lower than its bound tariff. This is:",
		[
			"Impossible in principle",
			"Possible: the binding is a ceiling within the applicable commitment",
			"Proof that all tariffs have been abolished",
			"Automatically the same as national treatment",
		],
		1,
		"The applied rate may be below the bound ceiling. Tariff bindings and national treatment are different legal concepts.",
	],
	[
		"e13",
		"MFN treatment generally concerns:",
		[
			"Non-discrimination among trading partners, subject to permitted exceptions",
			"Giving only one favoured state permanent exclusive access",
			"Eliminating every internal tax",
			"Guaranteeing equal export earnings",
		],
		0,
		"MFN is a non-discrimination principle among partners, with recognised exceptions. It does not guarantee outcomes or abolish every domestic tax.",
	],
	[
		"e14",
		"Digitising a land record automatically makes its underlying title correct and undisputed. This is:",
		[
			"Always true",
			"False: accuracy and legal title must be established separately",
			"True only because all land laws are identical",
			"True whenever the owner has a bank account",
		],
		1,
		"Digitisation can improve access and administration but may reproduce existing errors. Title rules and dispute resolution still matter.",
	],
	[
		"e15",
		"A country’s rank improves while its index score stays unchanged. Which is possible?",
		[
			"Other countries’ scores changed",
			"The country must have improved every underlying indicator",
			"Ranks cannot change without own-score improvement",
			"All indices use identical methodology",
		],
		0,
		"Rank is relative to other units and may change even without own-score improvement. Methods and country coverage also affect comparison.",
	],
	[
		"e16",
		"The most defensible way to assess an economic reform is to examine:",
		[
			"Only its slogan",
			"Mechanism, evidence, distribution, implementation and trade-offs",
			"Only one beneficiary’s story",
			"Only whether it raises one headline indicator",
		],
		1,
		"Policy assessment needs a causal mechanism, appropriate evidence and attention to competing objectives. Slogans or single anecdotes are insufficient.",
	],
	[
		"e17",
		"Inflation falls from 8% to 4%, with both rates positive. This is:",
		[
			"Deflation necessarily",
			"Disinflation",
			"An 8% fall in all prices",
			"Proof that the price level is unchanged",
		],
		1,
		"The price level is still rising, but more slowly. That is disinflation, not a fall in the general price level.",
	],
];
export const packQuestions = rows.map(
	([topic, text, options, answer, explanation], i) => ({
		id: `pe-q-${String(i + 1).padStart(3, "0")}`,
		topic: `pe-${topic}`,
		subject: topic[0] === "p" ? "Polity" : "Economy",
		text,
		options,
		answer,
		explanation,
		difficulty: i % 3 === 0 ? "Moderate" : "Easy",
		kind: "AI-generated",
		source:
			"Original AI-generated study question · reference review pending · not an official PYQ",
		year: null,
		tags: ["Polity–Economy pack", "Conceptual"],
		packId: "polity-economy-v1",
	}),
);
