import {execFileSync} from 'node:child_process';
import fs from 'node:fs/promises';
execFileSync('npm', ['run', 'build'], {stdio:'inherit', env:{...process.env, APP_BASE_PATH:'/awesome/'}});
// Only overwrite a deployment folder we previously generated.
try {
  await fs.access('docs');
  await fs.access('docs/.abhyas-generated');
  await fs.rm('docs', {recursive:true});
} catch (error) {
  if (error.code !== 'ENOENT') throw error;
  try { await fs.access('docs'); throw new Error('Refusing to replace an unrecognized docs directory'); }
  catch (check) { if(check.code !== 'ENOENT') throw check; }
}
await fs.cp('dist', 'docs', {recursive:true});
await fs.writeFile('docs/.nojekyll', '');
await fs.writeFile('docs/.abhyas-generated', 'Generated by npm run build:pages; do not edit compiled files.\n');
await fs.copyFile('Abhyas-Offline-Android.zip', 'docs/Abhyas-Offline-Android.zip');
console.log('GitHub Pages deployment generated in docs/ for /awesome/.');
